"""empty message

Revision ID: 7b23dd1f21fe
Revises: 5a686c9fca90
Create Date: 2017-03-21 10:26:05.564000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b23dd1f21fe'
down_revision = '5a686c9fca90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_user_role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['cms_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['cms_user.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    op.add_column(u'cms_user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column(u'cms_user', sa.Column('last_login_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'cms_user', 'last_login_time')
    op.drop_column(u'cms_user', 'is_active')
    op.drop_table('cms_user_role')
    op.drop_table('cms_role')
    # ### end Alembic commands ###
