"""empty message

Revision ID: be492a7dcfa2
Revises: db41c4547944
Create Date: 2017-04-01 00:32:33.223000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be492a7dcfa2'
down_revision = 'db41c4547944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlight_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'post', sa.Column('highlight_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'highlight_post', ['highlight_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column(u'post', 'highlight_id')
    op.drop_table('highlight_post')
    # ### end Alembic commands ###
