"""empty message

Revision ID: db41c4547944
Revises: fc0bc53a9989
Create Date: 2017-03-31 22:55:36.954000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db41c4547944'
down_revision = 'fc0bc53a9989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('is_removed', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('read_count', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'update_time')
    op.drop_column('post', 'read_count')
    op.drop_column('post', 'is_removed')
    op.drop_column('post', 'create_time')
    # ### end Alembic commands ###
