"""empty message

Revision ID: e27db3f75297
Revises: 0103db6aa109
Create Date: 2017-04-07 15:07:57.052000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27db3f75297'
down_revision = '0103db6aa109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('avatar', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'avatar')
    # ### end Alembic commands ###
